### ISSUE TITLE
Add a Docker entrypoint to choose what command to run on the image

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#44]
Suggestiong: If you use a shell script as an `ENTRYPOINT` you can keep the testing logic in one place. Here's server-syncstorage as an example: 

* [ENTRYPOINT](https://github.com/mozilla-services/server-syncstorage/blob/master/docker-entrypoint.sh) 
* [Dockerfile](https://github.com/mozilla-services/server-syncstorage/blob/master/Dockerfile#L9-L11)
* [usage in circle.yml](https://github.com/mozilla-services/server-syncstorage/blob/master/circle.yml#L34-L38)

testing in circle.yml
```yaml
test:
  override:
  - docker run -it app:build test_flake8
  - docker run -it app:build test_nose
  - docker run -it app:build test_functional
```
